module LanguageServer
  module Protocol
    module Interface
      class CodeActionRegistrationOptions
        def initialize: (document_selector: untyped, ?work_done_progress: bool, ?code_action_kinds: Array[String], ?resolve_provider: bool) -> void

        @attributes: Hash[Symbol, untyped]
        attr_reader attributes: Hash[Symbol, untyped]

        def to_hash: () -> Hash[Symbol, untyped]

        def to_json: (*untyped) -> String
      end
    end
  end
end
