module LanguageServer
  module Protocol
    module Interface
      class InitializeParams
        def initialize: (?work_done_token: untyped, process_id: Integer, ?client_info: untyped, ?locale: String, ?root_path: String, root_uri: String, ?initialization_options: untyped, capabilities: untyped, ?trace: untyped, ?workspace_folders: Array[untyped]) -> void

        @attributes: Hash[Symbol, untyped]
        attr_reader attributes: Hash[Symbol, untyped]

        def to_hash: () -> Hash[Symbol, untyped]

        def to_json: (*untyped) -> String
      end
    end
  end
end
