module LanguageServer
  module Protocol
    module Interface
      #
      # Returns inline value information as the complete text to be shown.
      #
      # @since 3.17.0
      #
      class InlineValueText
        def initialize: (range: untyped, text: String) -> void

        @attributes: Hash[Symbol, untyped]
        attr_reader attributes: Hash[Symbol, untyped]

        %a{pure}
        def range: () -> untyped

        %a{pure}
        def text: () -> String

        def to_hash: () -> Hash[Symbol, untyped]

        def to_json: (*untyped) -> String
      end
    end
  end
end
