module LanguageServer
  module Protocol
    module Interface
      #
      # A full diagnostic report with a set of related documents.
      #
      class RelatedFullDocumentDiagnosticReport
        def initialize: (kind: untyped, ?result_id: String, items: Array[untyped], ?related_documents: untyped) -> void

        @attributes: Hash[Symbol, untyped]
        attr_reader attributes: Hash[Symbol, untyped]

        def to_hash: () -> Hash[Symbol, untyped]

        def to_json: (*untyped) -> String
      end
    end
  end
end
