module LanguageServer
  module Protocol
    module Interface
      #
      # A string value used as a snippet is a template which allows to insert text
      # and to control the editor cursor when insertion happens.
      #
      # A snippet can define tab stops and placeholders with `$1`, `$2`
      # and `${3:foo}`. `$0` defines the final tab stop, it defaults to
      # the end of the snippet. Variables are defined with `$name` and
      # `${name:default value}`.
      #
      # @since 3.18.0
      #
      class StringValue
        def initialize: (kind: "snippet", value: String) -> void

        @attributes: Hash[Symbol, untyped]
        attr_reader attributes: Hash[Symbol, untyped]

        %a{pure}
        def kind: () -> "snippet"

        %a{pure}
        def value: () -> String

        def to_hash: () -> Hash[Symbol, untyped]

        def to_json: (*untyped) -> String
      end
    end
  end
end
