module LanguageServer
  module Protocol
    module Interface
      #
      # Defines workspace specific capabilities of the server.
      #
      # @since 3.18.0
      #
      class WorkspaceOptions
        def initialize: (?workspace_folders: untyped, ?file_operations: untyped, ?text_document_content: untyped) -> void

        @attributes: Hash[Symbol, untyped]
        attr_reader attributes: Hash[Symbol, untyped]

        %a{pure}
        def workspace_folders: () -> untyped

        %a{pure}
        def file_operations: () -> untyped

        %a{pure}
        def text_document_content: () -> untyped

        def to_hash: () -> Hash[Symbol, untyped]

        def to_json: (*untyped) -> String
      end
    end
  end
end
