version: 2.0
references:
  test: &test
    docker:
      - image: tmaier/docker-compose
        environment:
          COMPOSE_FILE: docker-compose.yml:docker-compose.ci.yml
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: setup
          command: |
            set -x
            docker info
            docker volume create project
            docker create -v project:/app --name project busybox chown -R 1000:1000 /app
            docker cp . project:/app
            docker start project
            docker-compose build $CIRCLE_JOB
      - run:
          name: test
          command: |
            docker-compose run $CIRCLE_JOB bundle exec rake test
            docker-compose run $CIRCLE_JOB RUBYOPT="--enable-frozen-string-literal" bundle exec rake test

jobs:
  ruby-2-6:
    <<: *test
  ruby-2-5:
    <<: *test
  ruby-2-4:
    <<: *test

workflows:
  version: 2
  test_and_buld:
    jobs:
      - ruby-2-6
      - ruby-2-5
      - ruby-2-4
