module LanguageServer
  module Protocol
    module Interface
      autoload :ApplyWorkspaceEditParams, "language_server/protocol/interface/apply_workspace_edit_params"
      autoload :ApplyWorkspaceEditResponse, "language_server/protocol/interface/apply_workspace_edit_response"
      autoload :CancelParams, "language_server/protocol/interface/cancel_params"
      autoload :ClientCapabilities, "language_server/protocol/interface/client_capabilities"
      autoload :CodeAction, "language_server/protocol/interface/code_action"
      autoload :CodeActionContext, "language_server/protocol/interface/code_action_context"
      autoload :CodeActionOptions, "language_server/protocol/interface/code_action_options"
      autoload :CodeActionParams, "language_server/protocol/interface/code_action_params"
      autoload :CodeActionRegistrationOptions, "language_server/protocol/interface/code_action_registration_options"
      autoload :CodeLens, "language_server/protocol/interface/code_lens"
      autoload :CodeLensOptions, "language_server/protocol/interface/code_lens_options"
      autoload :CodeLensParams, "language_server/protocol/interface/code_lens_params"
      autoload :CodeLensRegistrationOptions, "language_server/protocol/interface/code_lens_registration_options"
      autoload :Color, "language_server/protocol/interface/color"
      autoload :ColorInformation, "language_server/protocol/interface/color_information"
      autoload :ColorPresentation, "language_server/protocol/interface/color_presentation"
      autoload :ColorPresentationParams, "language_server/protocol/interface/color_presentation_params"
      autoload :ColorProviderOptions, "language_server/protocol/interface/color_provider_options"
      autoload :Command, "language_server/protocol/interface/command"
      autoload :CompletionContext, "language_server/protocol/interface/completion_context"
      autoload :CompletionItem, "language_server/protocol/interface/completion_item"
      autoload :CompletionList, "language_server/protocol/interface/completion_list"
      autoload :CompletionOptions, "language_server/protocol/interface/completion_options"
      autoload :CompletionParams, "language_server/protocol/interface/completion_params"
      autoload :CompletionRegistrationOptions, "language_server/protocol/interface/completion_registration_options"
      autoload :ConfigurationItem, "language_server/protocol/interface/configuration_item"
      autoload :ConfigurationParams, "language_server/protocol/interface/configuration_params"
      autoload :CreateFile, "language_server/protocol/interface/create_file"
      autoload :CreateFileOptions, "language_server/protocol/interface/create_file_options"
      autoload :DeleteFile, "language_server/protocol/interface/delete_file"
      autoload :DeleteFileOptions, "language_server/protocol/interface/delete_file_options"
      autoload :Diagnostic, "language_server/protocol/interface/diagnostic"
      autoload :DiagnosticRelatedInformation, "language_server/protocol/interface/diagnostic_related_information"
      autoload :DidChangeConfigurationParams, "language_server/protocol/interface/did_change_configuration_params"
      autoload :DidChangeTextDocumentParams, "language_server/protocol/interface/did_change_text_document_params"
      autoload :DidChangeWatchedFilesParams, "language_server/protocol/interface/did_change_watched_files_params"
      autoload :DidChangeWatchedFilesRegistrationOptions, "language_server/protocol/interface/did_change_watched_files_registration_options"
      autoload :DidChangeWorkspaceFoldersParams, "language_server/protocol/interface/did_change_workspace_folders_params"
      autoload :DidCloseTextDocumentParams, "language_server/protocol/interface/did_close_text_document_params"
      autoload :DidOpenTextDocumentParams, "language_server/protocol/interface/did_open_text_document_params"
      autoload :DidSaveTextDocumentParams, "language_server/protocol/interface/did_save_text_document_params"
      autoload :DocumentFilter, "language_server/protocol/interface/document_filter"
      autoload :DocumentFormattingParams, "language_server/protocol/interface/document_formatting_params"
      autoload :DocumentHighlight, "language_server/protocol/interface/document_highlight"
      autoload :DocumentLink, "language_server/protocol/interface/document_link"
      autoload :DocumentLinkOptions, "language_server/protocol/interface/document_link_options"
      autoload :DocumentLinkParams, "language_server/protocol/interface/document_link_params"
      autoload :DocumentLinkRegistrationOptions, "language_server/protocol/interface/document_link_registration_options"
      autoload :DocumentOnTypeFormattingOptions, "language_server/protocol/interface/document_on_type_formatting_options"
      autoload :DocumentOnTypeFormattingParams, "language_server/protocol/interface/document_on_type_formatting_params"
      autoload :DocumentOnTypeFormattingRegistrationOptions, "language_server/protocol/interface/document_on_type_formatting_registration_options"
      autoload :DocumentRangeFormattingParams, "language_server/protocol/interface/document_range_formatting_params"
      autoload :DocumentSymbolParams, "language_server/protocol/interface/document_symbol_params"
      autoload :ExecuteCommandOptions, "language_server/protocol/interface/execute_command_options"
      autoload :ExecuteCommandParams, "language_server/protocol/interface/execute_command_params"
      autoload :ExecuteCommandRegistrationOptions, "language_server/protocol/interface/execute_command_registration_options"
      autoload :FileEvent, "language_server/protocol/interface/file_event"
      autoload :FileSystemWatcher, "language_server/protocol/interface/file_system_watcher"
      autoload :FoldingRange, "language_server/protocol/interface/folding_range"
      autoload :FoldingRangeParams, "language_server/protocol/interface/folding_range_params"
      autoload :FoldingRangeProviderOptions, "language_server/protocol/interface/folding_range_provider_options"
      autoload :FormattingOptions, "language_server/protocol/interface/formatting_options"
      autoload :Hover, "language_server/protocol/interface/hover"
      autoload :InitializeError, "language_server/protocol/interface/initialize_error"
      autoload :InitializeParams, "language_server/protocol/interface/initialize_params"
      autoload :InitializeResult, "language_server/protocol/interface/initialize_result"
      autoload :InitializedParams, "language_server/protocol/interface/initialized_params"
      autoload :Location, "language_server/protocol/interface/location"
      autoload :LocationLink, "language_server/protocol/interface/location_link"
      autoload :LogMessageParams, "language_server/protocol/interface/log_message_params"
      autoload :MarkupContent, "language_server/protocol/interface/markup_content"
      autoload :Message, "language_server/protocol/interface/message"
      autoload :MessageActionItem, "language_server/protocol/interface/message_action_item"
      autoload :NotificationMessage, "language_server/protocol/interface/notification_message"
      autoload :ParameterInformation, "language_server/protocol/interface/parameter_information"
      autoload :Position, "language_server/protocol/interface/position"
      autoload :PublishDiagnosticsParams, "language_server/protocol/interface/publish_diagnostics_params"
      autoload :Range, "language_server/protocol/interface/range"
      autoload :ReferenceContext, "language_server/protocol/interface/reference_context"
      autoload :ReferenceParams, "language_server/protocol/interface/reference_params"
      autoload :Registration, "language_server/protocol/interface/registration"
      autoload :RegistrationParams, "language_server/protocol/interface/registration_params"
      autoload :RenameFile, "language_server/protocol/interface/rename_file"
      autoload :RenameFileOptions, "language_server/protocol/interface/rename_file_options"
      autoload :RenameOptions, "language_server/protocol/interface/rename_options"
      autoload :RenameParams, "language_server/protocol/interface/rename_params"
      autoload :RenameRegistrationOptions, "language_server/protocol/interface/rename_registration_options"
      autoload :RequestMessage, "language_server/protocol/interface/request_message"
      autoload :ResponseError, "language_server/protocol/interface/response_error"
      autoload :ResponseMessage, "language_server/protocol/interface/response_message"
      autoload :SaveOptions, "language_server/protocol/interface/save_options"
      autoload :ServerCapabilities, "language_server/protocol/interface/server_capabilities"
      autoload :ShowMessageParams, "language_server/protocol/interface/show_message_params"
      autoload :ShowMessageRequestParams, "language_server/protocol/interface/show_message_request_params"
      autoload :SignatureHelp, "language_server/protocol/interface/signature_help"
      autoload :SignatureHelpOptions, "language_server/protocol/interface/signature_help_options"
      autoload :SignatureHelpRegistrationOptions, "language_server/protocol/interface/signature_help_registration_options"
      autoload :SignatureInformation, "language_server/protocol/interface/signature_information"
      autoload :StaticRegistrationOptions, "language_server/protocol/interface/static_registration_options"
      autoload :SymbolInformation, "language_server/protocol/interface/symbol_information"
      autoload :TextDocumentChangeRegistrationOptions, "language_server/protocol/interface/text_document_change_registration_options"
      autoload :TextDocumentClientCapabilities, "language_server/protocol/interface/text_document_client_capabilities"
      autoload :TextDocumentContentChangeEvent, "language_server/protocol/interface/text_document_content_change_event"
      autoload :TextDocumentEdit, "language_server/protocol/interface/text_document_edit"
      autoload :TextDocumentIdentifier, "language_server/protocol/interface/text_document_identifier"
      autoload :TextDocumentItem, "language_server/protocol/interface/text_document_item"
      autoload :TextDocumentPositionParams, "language_server/protocol/interface/text_document_position_params"
      autoload :TextDocumentRegistrationOptions, "language_server/protocol/interface/text_document_registration_options"
      autoload :TextDocumentSaveRegistrationOptions, "language_server/protocol/interface/text_document_save_registration_options"
      autoload :TextDocumentSyncOptions, "language_server/protocol/interface/text_document_sync_options"
      autoload :TextEdit, "language_server/protocol/interface/text_edit"
      autoload :Unregistration, "language_server/protocol/interface/unregistration"
      autoload :UnregistrationParams, "language_server/protocol/interface/unregistration_params"
      autoload :VersionedTextDocumentIdentifier, "language_server/protocol/interface/versioned_text_document_identifier"
      autoload :WillSaveTextDocumentParams, "language_server/protocol/interface/will_save_text_document_params"
      autoload :WorkspaceClientCapabilities, "language_server/protocol/interface/workspace_client_capabilities"
      autoload :WorkspaceEdit, "language_server/protocol/interface/workspace_edit"
      autoload :WorkspaceFolder, "language_server/protocol/interface/workspace_folder"
      autoload :WorkspaceFoldersChangeEvent, "language_server/protocol/interface/workspace_folders_change_event"
      autoload :WorkspaceSymbolParams, "language_server/protocol/interface/workspace_symbol_params"

      require "language_server/protocol/interface/apply_workspace_edit_params"
      require "language_server/protocol/interface/apply_workspace_edit_response"
      require "language_server/protocol/interface/cancel_params"
      require "language_server/protocol/interface/client_capabilities"
      require "language_server/protocol/interface/code_action"
      require "language_server/protocol/interface/code_action_context"
      require "language_server/protocol/interface/code_action_options"
      require "language_server/protocol/interface/code_action_params"
      require "language_server/protocol/interface/code_action_registration_options"
      require "language_server/protocol/interface/code_lens"
      require "language_server/protocol/interface/code_lens_options"
      require "language_server/protocol/interface/code_lens_params"
      require "language_server/protocol/interface/code_lens_registration_options"
      require "language_server/protocol/interface/color"
      require "language_server/protocol/interface/color_information"
      require "language_server/protocol/interface/color_presentation"
      require "language_server/protocol/interface/color_presentation_params"
      require "language_server/protocol/interface/color_provider_options"
      require "language_server/protocol/interface/command"
      require "language_server/protocol/interface/completion_context"
      require "language_server/protocol/interface/completion_item"
      require "language_server/protocol/interface/completion_list"
      require "language_server/protocol/interface/completion_options"
      require "language_server/protocol/interface/completion_params"
      require "language_server/protocol/interface/completion_registration_options"
      require "language_server/protocol/interface/configuration_item"
      require "language_server/protocol/interface/configuration_params"
      require "language_server/protocol/interface/create_file"
      require "language_server/protocol/interface/create_file_options"
      require "language_server/protocol/interface/delete_file"
      require "language_server/protocol/interface/delete_file_options"
      require "language_server/protocol/interface/diagnostic"
      require "language_server/protocol/interface/diagnostic_related_information"
      require "language_server/protocol/interface/did_change_configuration_params"
      require "language_server/protocol/interface/did_change_text_document_params"
      require "language_server/protocol/interface/did_change_watched_files_params"
      require "language_server/protocol/interface/did_change_watched_files_registration_options"
      require "language_server/protocol/interface/did_change_workspace_folders_params"
      require "language_server/protocol/interface/did_close_text_document_params"
      require "language_server/protocol/interface/did_open_text_document_params"
      require "language_server/protocol/interface/did_save_text_document_params"
      require "language_server/protocol/interface/document_filter"
      require "language_server/protocol/interface/document_formatting_params"
      require "language_server/protocol/interface/document_highlight"
      require "language_server/protocol/interface/document_link"
      require "language_server/protocol/interface/document_link_options"
      require "language_server/protocol/interface/document_link_params"
      require "language_server/protocol/interface/document_link_registration_options"
      require "language_server/protocol/interface/document_on_type_formatting_options"
      require "language_server/protocol/interface/document_on_type_formatting_params"
      require "language_server/protocol/interface/document_on_type_formatting_registration_options"
      require "language_server/protocol/interface/document_range_formatting_params"
      require "language_server/protocol/interface/document_symbol_params"
      require "language_server/protocol/interface/execute_command_options"
      require "language_server/protocol/interface/execute_command_params"
      require "language_server/protocol/interface/execute_command_registration_options"
      require "language_server/protocol/interface/file_event"
      require "language_server/protocol/interface/file_system_watcher"
      require "language_server/protocol/interface/folding_range"
      require "language_server/protocol/interface/folding_range_params"
      require "language_server/protocol/interface/folding_range_provider_options"
      require "language_server/protocol/interface/formatting_options"
      require "language_server/protocol/interface/hover"
      require "language_server/protocol/interface/initialize_error"
      require "language_server/protocol/interface/initialize_params"
      require "language_server/protocol/interface/initialize_result"
      require "language_server/protocol/interface/initialized_params"
      require "language_server/protocol/interface/location"
      require "language_server/protocol/interface/location_link"
      require "language_server/protocol/interface/log_message_params"
      require "language_server/protocol/interface/markup_content"
      require "language_server/protocol/interface/message"
      require "language_server/protocol/interface/message_action_item"
      require "language_server/protocol/interface/notification_message"
      require "language_server/protocol/interface/parameter_information"
      require "language_server/protocol/interface/position"
      require "language_server/protocol/interface/publish_diagnostics_params"
      require "language_server/protocol/interface/range"
      require "language_server/protocol/interface/reference_context"
      require "language_server/protocol/interface/reference_params"
      require "language_server/protocol/interface/registration"
      require "language_server/protocol/interface/registration_params"
      require "language_server/protocol/interface/rename_file"
      require "language_server/protocol/interface/rename_file_options"
      require "language_server/protocol/interface/rename_options"
      require "language_server/protocol/interface/rename_params"
      require "language_server/protocol/interface/rename_registration_options"
      require "language_server/protocol/interface/request_message"
      require "language_server/protocol/interface/response_error"
      require "language_server/protocol/interface/response_message"
      require "language_server/protocol/interface/save_options"
      require "language_server/protocol/interface/server_capabilities"
      require "language_server/protocol/interface/show_message_params"
      require "language_server/protocol/interface/show_message_request_params"
      require "language_server/protocol/interface/signature_help"
      require "language_server/protocol/interface/signature_help_options"
      require "language_server/protocol/interface/signature_help_registration_options"
      require "language_server/protocol/interface/signature_information"
      require "language_server/protocol/interface/static_registration_options"
      require "language_server/protocol/interface/symbol_information"
      require "language_server/protocol/interface/text_document_change_registration_options"
      require "language_server/protocol/interface/text_document_client_capabilities"
      require "language_server/protocol/interface/text_document_content_change_event"
      require "language_server/protocol/interface/text_document_edit"
      require "language_server/protocol/interface/text_document_identifier"
      require "language_server/protocol/interface/text_document_item"
      require "language_server/protocol/interface/text_document_position_params"
      require "language_server/protocol/interface/text_document_registration_options"
      require "language_server/protocol/interface/text_document_save_registration_options"
      require "language_server/protocol/interface/text_document_sync_options"
      require "language_server/protocol/interface/text_edit"
      require "language_server/protocol/interface/unregistration"
      require "language_server/protocol/interface/unregistration_params"
      require "language_server/protocol/interface/versioned_text_document_identifier"
      require "language_server/protocol/interface/will_save_text_document_params"
      require "language_server/protocol/interface/workspace_client_capabilities"
      require "language_server/protocol/interface/workspace_edit"
      require "language_server/protocol/interface/workspace_folder"
      require "language_server/protocol/interface/workspace_folders_change_event"
      require "language_server/protocol/interface/workspace_symbol_params"
    end
  end
end
