module LanguageServer
  module Protocol
    module Constant
      #
      # Predefined error codes.
      #
      module ErrorCodes
        PARSE_ERROR: -32700
        INVALID_REQUEST: -32600
        METHOD_NOT_FOUND: -32601
        INVALID_PARAMS: -32602
        INTERNAL_ERROR: -32603
        #
        # Error code indicating that a server received a notification or
        # request before the server has received the `initialize` request.
        #
        SERVER_NOT_INITIALIZED: -32002
        UNKNOWN_ERROR_CODE: -32001
      end
    end
  end
end
