module LanguageServer
  module Protocol
    module Constant
      #
      # The message type
      #
      module MessageType
        #
        # An error message.
        #
        ERROR: 1
        #
        # A warning message.
        #
        WARNING: 2
        #
        # An information message.
        #
        INFO: 3
        #
        # A log message.
        #
        LOG: 4
        #
        # A debug message.
        #
        # @since 3.18.0
        #
        DEBUG: 5
      end
    end
  end
end
