module LanguageServer
  module Protocol
    module Constant
      #
      # Regular Expression Engines
      #
      module RegularExpressionEngineKind
        ES2020: 'ES2020'
      end
    end
  end
end
